### ISSUE TITLE
[docs] Amend "primaryColor" usage in "Example rendering icons (FontAwesome, regular Images)"

### ISSUE THREAD

**Issue by 509dave16** [nicotroia/react-native-floating-action-menu#1]
@nicotroia Shouldn't the `primaryColor` be accessed on the `menuState` passed to the `renderItemIcon` callback instead of on `this.state` ?
![Screen Shot 2020-06-21 at 10 23 46 AM](https://user-images.githubusercontent.com/2925882/85231172-ef11fd80-b3a9-11ea-84fc-d4e8e1ff6eed.png)

**Comment by nicotroia** [comment]
@509dave16 ah actually no, but this is a confusing example. The "primaryColor" can be any constant in-line or imported from somewhere. When I made this example, I must have had it in my state. I'll update the readme example

This would be a more real-world example:

```js
const items = [...];
const primaryColor = '#09f';

const renderItem = () => {
  const iconColor = isPressed ? '#fff' : primaryColor;
}
```

**Comment by nicotroia** [comment]
Going to close this. Feel free to ask other questions though
