### ISSUE TITLE
add change style of menu and item buttons

### ISSUE THREAD

**Issue by jsuyog2** [nicotroia/react-native-floating-action-menu#13]

**Comment by nicotroia** [comment]
Sorry I haven't written any documentation for this yet, but I have added recently the ability to add these props to the FloatingItem config objects:

```
  style,
  containerStyle,
  labelStyle,
  buttonStyle,
  buttonInnerStyle,
```

and these are available on the FloatingMenu element:

```
  buttonOuterStyle,
  buttonTouchableStyle,
  buttonInnerStyle,
  dimmerStyle,
```

**Comment by nicotroia** [comment]
I will close for now, please reopen if it doesn't help what you need
